doanweb/Controllers/CustomerController.cs
using doanweb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace doanweb.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        dbSanPhamDataContext data = new dbSanPhamDataContext();
        public ActionResult Index(int? page, string searchString, string cateid = null)
        {
            var all_khachhang = from s in data.KHACH_HANGs select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                all_khachhang = all_khachhang.Where(p => p.HoTenKH.Contains(searchString));
            }

            if (page == null)
                page = 1;
            int pageSize = 16;
            int pageNum = page ?? 1;
            return View(all_khachhang.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Detail(string id)
        {
            var D_sanpham = data.KHACH_HANGs.Where(m => m.MaKH.StartsWith(id)).First();
            return View(D_sanpham);
        }
        [HttpPost]
        public ActionResult Detail(string id, FormCollection collection)
        {
            var E_khachhang = data.KHACH_HANGs.First(m => m.MaKH == id);
            var E_tendangnhap = collection["TenDangNhapTK"];
            var E_hoten = collection["HoTenKH"];
            var E_sdt = collection["SDT"];
            var E_diachi = collection["DiaChi"];
            var E_email = collection["Email"];
            if (string.IsNullOrEmpty(E_tendangnhap))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                E_khachhang.TenDangNhapTK = E_tendangnhap.ToString();
                E_khachhang.HoTenKH = E_hoten.ToString();
                E_khachhang.SDT = E_sdt.ToString();
                E_khachhang.DiaChi = E_diachi.ToString();
                E_khachhang.Email = E_email.ToString();
                UpdateModel(E_khachhang);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Detail(id);
        }
        public ActionResult Delete(string id)
        {
            var D_Sach = data.KHACH_HANGs.First(m => m.MaKH == id);
            return View(D_Sach);
        }
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            var D_Sach = data.KHACH_HANGs.Where(m => m.MaKH == id).First();
            data.KHACH_HANGs.DeleteOnSubmit(D_Sach);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

doanweb/Controllers/NhanVienController.cs
using doanweb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace doanweb.Controllers
{
    public class NhanVienController : Controller
    {
        // GET: Products
        dbSanPhamDataContext data = new dbSanPhamDataContext();
        public ActionResult Index(int? page, string searchString, int cateid = 0)
        {
            var all_sanpham = from s in data.NHAN_VIENs select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                all_sanpham = all_sanpham.Where(p => p.HoTen.Contains(searchString));
            }

            ViewBag.ChucVuNV = new SelectList(data.CHUC_VUs, "MaCV", "ChucVu");
            

            if (page == null)
                page = 1;
            /* var all_book = (from Sach in data.Saches select Sach).OrderBy(m => m.masach);*/
            int pageSize = 16;
            int pageNum = page ?? 1;
            return View(all_sanpham.ToPagedList(pageNum, pageSize));
        }
        // GET: NhanVien
        public ActionResult Create()
        {
            ViewBag.ChucVu = new SelectList(data.CHUC_VUs, "MaCV", "ChucVU");
          
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, NHAN_VIEN s, string catecvid)
        {
            var E_manv = collection["MaNV"];
            var E_tennv = collection["HoTen"];
            var E_useraccount = collection["TenDangNhapTK"];
            var E_SDT = collection["SDT"];
            var E_diachi = collection["DiaChi"];
            var E_email = collection["Email"];
            
            if (string.IsNullOrEmpty(E_manv))
            {
                ViewData["Error"] = "Don't empty";
            }
            else if (catecvid != null)
            {
                s.MaNV = E_manv.ToString();
                s.MaCV = catecvid;

                var user = data.TAI_KHOANs.SingleOrDefault( e => e.TenDangNhapTK == E_useraccount);
                if(user == null)
                {
                    TAI_KHOAN dktk = new TAI_KHOAN();
                    dktk.TenDangNhapTK = E_useraccount.ToString();
                    dktk.MatKhau = "123";
                    data.TAI_KHOANs.InsertOnSubmit(dktk);
                    data.SubmitChanges();
                }

                s.TenDangNhapTK = E_useraccount;
                s.HoTen = E_tennv.ToString();
                s.SDT = E_SDT;
                s.Email = E_email;
                s.DiaChi = E_diachi;

                data.NHAN_VIENs.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        public ActionResult Edit(string id)
        {
            
            var D_sanpham = data.NHAN_VIENs.Where(m => m.MaNV.StartsWith(id)).First();
            return View(D_sanpham);
        }
        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            var E_nv = data.NHAN_VIENs.First(m => m.MaNV == id);
            
            var E_tennv = collection["HoTen"];
            var E_pass = collection["MatKhau"];
            var E_SDT = collection["SDT"];
            var E_diachi = collection["DiaChi"];
            var E_email = collection["Email"];
            var E_manv = E_nv.MaNV;
            if (string.IsNullOrEmpty(E_manv))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
               E_nv.HoTen = E_tennv;
                TAI_KHOAN tk = data.TAI_KHOANs.SingleOrDefault(s => s.TenDangNhapTK == E_nv.TenDangNhapTK);
                if(tk != null)
                {
                    tk.MatKhau = E_pass;
                    data.SubmitChanges();
                }
                E_nv.DiaChi = E_diachi;
                E_nv.SDT = E_SDT;
                E_nv.Email = E_email;
                UpdateModel(E_nv);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        public ActionResult Delete(string id)
        {
            var D_Sach = data.NHAN_VIENs.First(m => m.MaNV == id);
            return View(D_Sach);
        }
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            var D_Sach = data.NHAN_VIENs.Where(m => m.MaNV == id).First();
            data.NHAN_VIENs.DeleteOnSubmit(D_Sach);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

doanweb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using doanweb.Models;
using PagedList;

namespace doanweb.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        dbSanPhamDataContext data = new dbSanPhamDataContext();
        public ActionResult Index(int? page, string searchString, int cateid = 0)
        {
            var all_sanpham = from s in data.SAN_PHAMs select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                all_sanpham = all_sanpham.Where(p => p.TenSP.Contains(searchString));
            }

            ViewBag.LoaiSP = new SelectList(data.Loai_SPs, "Ma_Loai", "TenLoai");
            if (cateid != 0)
            {
                var sanpham_with_category = data.Loai_SPs.Where(s => s.Ma_Loai == cateid).FirstOrDefault();
                all_sanpham = all_sanpham.Where(p => p.Ma_Loai == sanpham_with_category.Ma_Loai);
            }

            if (page == null)
                page = 1;
            /* var all_book = (from Sach in data.Saches select Sach).OrderBy(m => m.masach);*/
            int pageSize = 16;
            int pageNum = page ?? 1;
            return View(all_sanpham.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Create()
        {
            ViewBag.LoaiSP = new SelectList(data.Loai_SPs, "Ma_Loai", "TenLoai");
            ViewBag.MaPhanLoai = new SelectList(data.PhanLoais, "MaPhanLoai", "TenPhanLoai");
            ViewBag.MaThuongHieu = new SelectList(data.THUONG_HIEUs, "Ma_TH", "TenTH");
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, SAN_PHAM s, int cateid = 0,int idtypeSP = 0,int brandid = 0)
        {
            var E_masp = collection["MaSP"];
            var E_tensp = collection["TenSP"];
            var E_hinhsp = collection["HinhAnhSP"];
            var E_hinhphu1 = collection["HinhAnhCT1"];
            var E_hinhphu2 = collection["HinhAnhCT2"];
            var E_hinhphu3 = collection["HinhAnhCT3"];
            var E_hinhphu4 = collection["HinhAnhCT4"];
            var E_giaban = Convert.ToDecimal(collection["Gia"]);
            var E_soluong = Convert.ToInt32(collection["SoLuong"]);
            var E_id = Convert.ToInt32(collection["ID"]);
            if (string.IsNullOrEmpty(E_masp))
            {
                ViewData["Error"] = "Don't empty";
            }
            else 
            {
                if (idtypeSP != 0 )
                {
                    s.Ma_Loai = idtypeSP;
                }
                if(cateid != 0 )
                {
                    s.MaPhanLoai = cateid;
                }    
                if(brandid !=0)
                {
                    s.Ma_TH = brandid;
                }
                s.SLTruyCap = 0;
                s.MaSP = E_masp.ToString();
                s.TenSP = E_tensp.ToString();
                s.HinhAnhSP = E_hinhsp.ToString();
                s.HinhAnhCT1 = E_hinhphu1.ToString();
                s.HinhAnhCT2 = E_hinhphu2.ToString();
                s.HinhAnhCT3 = E_hinhphu3.ToString();
                s.HinhAnhCT4 = E_hinhphu4.ToString();
                s.Gia = E_giaban;
                s.SoLuong = E_soluong;
                data.SAN_PHAMs.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }

        public ActionResult Edit(string id)
        {
            ViewBag.LoaiSP = new SelectList(data.Loai_SPs, "Ma_Loai", "TenLoai");
            ViewBag.MaPhanLoai = new SelectList(data.PhanLoais, "MaPhanLoai", "TenPhanLoai");
            ViewBag.MaThuongHieu = new SelectList(data.THUONG_HIEUs, "Ma_TH", "TenTH");
            var D_sanpham = data.SAN_PHAMs.Where(m => m.MaSP.StartsWith(id)).First();
            return View(D_sanpham);
        }
        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            var E_sanpham = data.SAN_PHAMs.First(m => m.MaSP == id);
            var E_masp = collection["MaSP"];
            var E_tensp = collection["TenSP"];
            var E_hinhsp = collection["HinhAnhSP"];
            var E_hinhphu1 = collection["HinhAnhCT1"];
            var E_hinhphu2 = collection["HinhAnhCT2"];
            var E_hinhphu3 = collection["HinhAnhCT3"];
            var E_hinhphu4 = collection["HinhAnhCT4"];
            var E_giaban = Convert.ToDecimal(collection["Gia"]);
            var E_soluong = Convert.ToInt32(collection["SoLuong"]);
            var E_id = Convert.ToInt32(collection["ID"]);
            if (string.IsNullOrEmpty(E_masp))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                E_sanpham.MaSP = E_masp.ToString();
                E_sanpham.TenSP = E_tensp.ToString();
                E_sanpham.HinhAnhSP = E_hinhsp.ToString();
                E_sanpham.HinhAnhCT1 = E_hinhphu1.ToString();
                E_sanpham.HinhAnhCT2 = E_hinhphu2.ToString();
                E_sanpham.HinhAnhCT3 = E_hinhphu3.ToString();
                E_sanpham.HinhAnhCT4 = E_hinhphu4.ToString();
                E_sanpham.Gia = E_giaban;
                E_sanpham.SoLuong = E_soluong;
                UpdateModel(E_sanpham);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        public ActionResult Delete(string id)
        {
            var D_Sach = data.SAN_PHAMs.First(m => m.MaSP == id);
            return View(D_Sach);
        }
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            var D_Sach = data.SAN_PHAMs.Where(m => m.MaSP == id).First();
            data.SAN_PHAMs.DeleteOnSubmit(D_Sach);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

doanweb/Controllers/TypeProductAdminController.cs
using doanweb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace doanweb.Controllers
{
    public class TypeProductAdminController : Controller
    {
        dbSanPhamDataContext data = new dbSanPhamDataContext();
        // GET: TypeProductAdmin
        public ActionResult DanhSachDanhMuc()
        {
            var all_thongke = from l in data.Loai_SPs select l;
                              
                            

            return View(all_thongke.ToList());
        }

        public ActionResult DanhSachThuongHieu()
        {
            var all_thongke = from l in data.THUONG_HIEUs select l;



            return View(all_thongke.ToList());
        }



//Xóa
        public ActionResult Delete(int idtype)
        {
            var D_Sach = data.Loai_SPs.First(m => m.Ma_Loai == idtype);
            return View(D_Sach);
        }
        [HttpPost]
        public ActionResult Delete(int idtype, FormCollection collection)
        {
            var D_Sach = data.Loai_SPs.Where(m => m.Ma_Loai == idtype).First();
            data.Loai_SPs.DeleteOnSubmit(D_Sach);
            data.SubmitChanges();
            return RedirectToAction("DanhSachDanhMuc");
        }

        public ActionResult DeleteTH(int idbrand)
        {
            var D_Sach = data.THUONG_HIEUs.First(m => m.Ma_TH == idbrand);
            return View(D_Sach);
        }
        [HttpPost]
        public ActionResult DeleteTH(int idbrand, FormCollection collection)
        {
            var D_Sach = data.THUONG_HIEUs.Where(m => m.Ma_TH == idbrand).First();
            data.THUONG_HIEUs.DeleteOnSubmit(D_Sach);
            data.SubmitChanges();
            return RedirectToAction("DanhSachThuongHieu");
        }



//Thêm
        public ActionResult ThemDanhMuc()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemDanhMuc(FormCollection collection, Loai_SP s)
        {

            var E_tendm = collection["TenLoai"];
            if (string.IsNullOrEmpty(E_tendm))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                
                s.TenLoai = E_tendm;
                data.Loai_SPs.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("DanhSachDanhMuc");
            }
            return this.ThemDanhMuc();
        }

        public ActionResult ThemTH()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemTH(FormCollection collection, THUONG_HIEU s)
        {

            var E_tenth = collection["TenTH"];
            if (string.IsNullOrEmpty(E_tenth))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {

                s.TenTH = E_tenth;
                data.THUONG_HIEUs.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("DanhSachThuongHieu");
            }
            return this.ThemDanhMuc();
        }
    }
}

doanweb/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="~/Content/css/admin-index.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        @*<span class="icon"><ion-icon name="storefront"></ion-icon></span>*@
                        <img src="~/Content/images/vz tách nền.jpg" width="80" />
                        <span class="title">Vz</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("ThongKe","ThongKe")">
                        <span class="icon"><ion-icon name="home-outline"></ion-icon></span>
                        <span class="title">Trang chủ</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Customer")">
                        <span class="icon"><ion-icon name="people-outline"></ion-icon></span>
                        <span class="title">Khách hàng</span>
                    </a>
                </li>
                @if (Session["NhanVienCapCao"] != null)
                {

                    <li>
                        <a href="@Url.Action("Index","NhanVien")">
                            <span class="icon"><ion-icon name="man-outline"></ion-icon></span>
                            <span class="title">Nhân Viên</span>
                        </a>
                    </li>
                }
                else if (Session["NhanVienCapThap"] != null)
                {

                }

                <li>
                    <a href="@Url.Action("DanhSachDanhMuc","TypeProductAdmin")">
                        <span class="icon"><ion-icon name="reorder-four-outline"></ion-icon></span>
                        <span class="title">Danh mục sản phẩm</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("DanhSachThuongHieu","TypeProductAdmin")">
                        <span class="icon"><ion-icon name="reorder-four-outline"></ion-icon></span>
                        <span class="title">Thương hiệu sản phẩm</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Products")">
                        <span class="icon"><i class='bx bx-box'></i></span>
                        <span class="title">Sản phẩm</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("DangXuat", "Account", new { @outURL = Request.Url.ToString() })">
                        <span class="icon"><ion-icon name="log-out-outline"></ion-icon></span>
                        <span class="title">Đăng xuất</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- main -->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>
                <!-- <div class="search">
                    <label>
                        <input type="text" placeholder = "Search here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div> -->
            </div>

            <!-- cards -->

            @RenderBody()
            <!-- order detail list -->
            <!-- order detail list -->

        </div>
    </div>
    <script src="~/Content/js/admin-script.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)
    @RenderSection("uploadct1", required: false)
    @RenderSection("uploadct2", required: false)
    @RenderSection("uploadct3", required: false)
    @RenderSection("uploadct4", required: false)
</body>
</html>

doanweb/Views/Shared/_Layout.cshtml
@using doanweb.Models
<style>
    .Card .CardInner .container .Icon {
        display: flex;
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<link href="../../Content/css/style.css" rel="stylesheet" />*@
    <link href="../../Content/fonts/fontawesome-free-6.2.1-web/fontawesome-free-6.2.1-web/css/all.css" rel="stylesheet" />
    <title>shop</title>
</head>
<body>
    <header>
        <section id="header">
           
            <img src="~/Content/images/vz tách nền.jpg" width="100" />
            @using (Html.BeginForm("Productlist", "Home", FormMethod.Get, new { @class = "form-inline" }))
            {
                <div class="Card">
                    <div class="CardInner">
                        <div class="container">
                            <div class="Icon">
                                <input type="Text" class="form-control col-md-10" value="@ViewBag.Keyword" name="searchString" placeholder="Tìm kiếm sản phẩm..." />
                                <button type="submit" class="btn-search"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#657789" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /></svg></button>
                            </div>
                            @*<div class="InputContainer">

                            <input type="submit" class="btn btn-info" value="Tìm " style="margin-left:10px;">
                        </div>*@
                        </div>
                    </div>
                </div>

            }

            <div>
                <ul id="navbar">
                    <li><a class="active" href="@Url.Action("Index","Home")">TRANG CHỦ</a></li>
                    <li><a href="@Url.Action("Contact","Home")">GIỚI THIỆU</a></li>

                    <li>
                        <a href="@Url.Action("Productlist","Home")">SẢN PHẨM</a>
                        @*<ul class="sub-menu">

                            <li><a href=""></a></li>
                            <ul class="brand">
                                <li></li>
                                <li>Logitech</li>
                                <li>Akko</li>
                                <li>Leopard</li>
                            </ul>

                        <li><a href="">Bàn phím máy tính</a></li>
                        <ul class="brand">
                            <li>Kit bàn phím</li>
                            <li>Logitech</li>
                            <li>Akko</li>
                            <li>Leopard</li>
                        </ul>
                        <li><a href="">Chuột máy tính</a></li>
                        <ul class="brand">
                            <li>Asus</li>
                            <li>Logitech</li>
                        </ul>
                        <li><a href="">Lót chuột</a></li>
                        <ul class="brand">
                            <li>Dare-u</li>
                            <li>Corsair</li>
                        </ul>
                        <li><a href="">Bàn máy tính</a></li>
                        <ul class="brand">
                            <li>Bàn gỗ</li>
                            <li>E-dra</li>
                        </ul>
                        <li><a href="">Ghế ngồi</a></li>
                        <ul class="brand">
                            <li>Anda Seat</li>
                            <li>AK racing</li>
                        </ul>
                        <li><a href="">Màn hình máy tính</a></li>
                        <ul class="brand">
                            <li>LG</li>
                            <li>DELL</li>
                        </ul>
                        <li><a href="">Tay nâng màn hình</a></li>
                        <ul class="brand">
                            <li>North Bayou</li>
                            <li>Human Motion</li>
                        </ul>
                        <li><a href="">Giá đỡ laptop</a></li>
                        <ul class="brand">
                            <li>HyperWork</li>
                            <li>Havit</li>
                        </ul>
                        <li><a href="">Webcam</a></li>
                        <ul class="brand">
                            <li>Rapoo </li>
                            <li>Thronmax </li>
                        </ul>
                    </ul>*@
                    </li>
                    <li><a href="#">CHÍNH SÁCH BẢO HIỂM</a></li>
                    @if (Session["KhachHang"] == null)
                    {
                        if (Session["NhanVien"] == null)
                        {
                            <li><a href="@Url.Action("DangNhap","Account")"><i class="fa fa-shopping-bag"></i></a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Index","Home")"><i class="fa fa-shopping-bag"></i></a></li>
                        }
                    }
                    else
                    {
                        //Dùng Url.Action để truy cập vào giỏ hàng
                        <li><a href="@Url.Action("GioHang","GioHang")"><i class="fa fa-shopping-bag"></i></a></li>
                    }

                    <li>
                        @if (Session["KhachHang"] == null)
                        {
                            //Nếu chưa đăng nhập gì cả
                            if (Session["NhanVien"] == null)
                            {
                                <a href="#"><i class="fa fa-user"></i></a>
                            }
                            else //Nếu đăng nhập tài khoản nhân viên
                            {
                                //Thay đường dẫn để nối đến trang thống kê của Admin
                                <a href="@Url.Action("ThongKe","ThongKe")"><i class="fa fa-user"></i></a>
                            }

                            <ul class="sub-menu-user">

                                @if (Session["NhanVien"] == null)
                                {
                                    <li>@Html.ActionLink("Sign up", "DangKy", "Account")</li>
                                    <li>@Html.ActionLink("Login", "DangNhap", "Account")</li>
                                }
                                else
                                {

                                    <li><a href="@Url.Action("DangXuat", "Account", new { @outURL = Request.Url.ToString() })"> Log out</a></li>

                                }

                            </ul>
                        }
                        else
                        {
                            <a href="@Url.Action("ThongTin","Account", new { @taikhoan = (Session["KhachHang"] as KHACH_HANG).MaKH.ToString().TrimEnd(' ') })"><i class="fa fa-user"></i></a>
                            <ul class="sub-menu-user">
                                <li><a href="@Url.Action("DangXuat", "Account", new { @outURL = Request.Url.ToString() })"> Log out</a></li>
                            </ul>
                        }

                    </li>

                </ul>
            </div>
        </section>
    </header>

    @RenderBody()

    <footer class="footer">
        <div class="footer-container">
            <div class="row">
                <div class="footer-col">
                    <h4>Cửa hàng</h4>
                    <ul>
                        <li><a href="#">Giới thiệu</a></li>
                        <li><a href="#">Dịch vụ</a></li>
                        <li><a href="#">Giấy phép</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Hổ trợ</h4>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Phương thức thanh toán</a></li>
                        <li><a href="#">Chính sách bảo hành</a></li>
                        <li><a href="#">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Online Shopping</h4>
                    <ul>
                        <li><a href="#">Trang chủ</a></li>
                        <li><a href="#">Giỏ hàng</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>follow us</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/Content/js/script.js"></script>
</body>
</html>

doanweb/Views/Shared/_slider.cshtml
<section class="slider-container">
    <div class="slider-wrapper">
        <div class="slider">
            <img id="slide-1" src="~/Content/images/leaf65.jpg" alt="">
            <img id="slide-2" src="~/Content/images/banner.jpg" alt="">
            <img id="slide-3" src="~/Content/images/hg00.jpg" alt="">
            <img id="slide-4" src="~/Content/images/rx-780-2.jpg" alt="">
        </div>
    </div>
</section>